### ISSUE TITLE
Does this repo have an admin?

### ISSUE THREAD

**Issue by amp64** [AreYouFreeBusy/AlexaSkillsKit.NET#34]
Looks like this awesome project has stalled as the admin has vanished. Can they come back please? Or add admin rights to someone with more time/inclination to continue with this fine project?

**Comment by stefann42** [comment]
Admin hasn't left :) and I'm watching the issues and discussions. It pains me that I don't have the time to do the merges, but our business is growing and there are more important tasks we have to complete and until we can come up for air I won't be able to move this project forward.

I'd be glad to accept someone as co-admin although it would have to someone who's be willing to work with me on code reviews because sometimes pull requests have to be rewritten to maintain a high quality bar for the codebase (we use this library in our commercial codebase and we can't have a lower quality just for the sake of moving the project forward).

I'm not suggesting the pending PRs are not quality code (haven't had time to review them) just explaining why the project for stalling.

Thanks for your assistance with the issues and for your willingness to help.


On Jun 17, 2017, at 3:15 PM, amp64 <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like this awesome project has stalled as the admin has vanished. Can they come back please? Or add admin rights to someone with more time/inclination to continue with this fine project?

**Comment by ElvenMonky** [comment]
I have follow up question on this. Amazon resently become really active in expanding their development for Alexa platform. It looks like you should expect much more people to come for your library in nearest future.  Probably, you can find some time to look for someone who can help you with reviews and merges.

Also, as far as I can see the Amazon's [alexa-skills-kit-java](https://github.com/amzn/alexa-skills-kit-java) project was directly ported from version 1.4.0 of your project (Btw, I didn't know that MIT license allows to do so without any notice of original License and Author). Perhaps it's time to pickup their modifications back to this project. I believe I can do it in few days.

**Comment by stefann42** [comment]
@ElvenMonky I agree and I plan to spend time in December catching up on the Alexa platform and on this project. In the meantime, I added you as a contributor with write access and it would be great to work together. Please do merge all the PRs. Email me direct at stefan@freebusy.io for questions or to discuss. Thanks for offering to help!

**Comment by ElvenMonky** [comment]
Thanks @stefann42, I appresiate this. It would be great for me to participate in project growth.

**Comment by stefann42** [comment]
Thanks to help from @ElvenMonky we now have release v1.6.0 which brings AlexaSkillsKit.NET up-to-date with the latest Alexa SDK.
