### ISSUE TITLE
Doesn't validate certificate for incoming request (according to Cert team)

### ISSUE THREAD

**Issue by rscott78** [AreYouFreeBusy/AlexaSkillsKit.NET#5]
I'm using your library for my Alexa skill (great job on it btw!)

For the past several months, I've been working with the cert team to get my skill approved (this frustration is a topic for another day though). Through January, they would come back with requested changes to the behavior of the skill. 

Since around mid-Feburary, Amazon has started rejected my attempts because they say that `The skill does not validate the certificates for the incoming requests and is accepting requests with incorrect certificate. Please refer to the document that describes how to build your Alexa Skill as a web service` I racked my brain about what I could have changed and finally blew away my full library and updated it again from virgin source (i.e, I've made no changes to it). 

Again, I received a rejection saying the same thing. Has anyone else noticed this? Could Amazon have changed their process and made it incompatible with the current library per chance?

Finally, how would I go about testing this piece - is there a way to get Amazon to send me a bogus request that I can debug against?

**Comment by brendan-murphy** [comment]
I noticed this same thing. I had received 4-5 emails from Amazon giving me feedback about my skill never mentioning any problems with certificate validation, but then I got one recently with the same certificate validation critic without changing anything on my end. I did however make changes after that to validate the date of the request and then the next feedback from Amazon did not mention any problems with validation. I too am curious of what is a good way to test bogus requests.

**Comment by rscott78** [comment]
@brendan-murphy So it sounds like you got yours past certification by making that date fix? Could you outline the changes you made on your end (maybe fork or pull request) so we can all benefit from it?

**Comment by stefann42** [comment]
Hi guys, you don't need the Alexa cert team to test this. You can test it yourself against your own skill (and you should) prior to submitting for certification by sending an invalid request to your skill's endpoint. From a signature validation request perspective an invalid request
1. is missing the SignatureCertChainUrl header and/or
2. is missing the Signature header and/or 
3. the signature value in the Signature header can't be validated using the certificate supplied in the SignatureCertChainUrl header
4. the certificate supplied in the SignatureCertChainUrl header has expired
5. the certificate supplied in the SignatureCertChainUrl header isn't meant for the echo-api.amazon.com
6. the timestamp supplied in the request occurs too much in the past 

You can test for all these scenarios using a HTTP tool like Fiddler or cURL. For example for this sample request exhibits (3) and (6) 

```
curl -H "Content-Type: application/json" -H "SignatureCertChainUrl: https://s3.amazonaws.com/echo.api/echo-api-cert-2.pem" -H "Signature: OMEN68E8S0H9vTHRBVQMmWxeXLV8hpQoodoU6NdLAUB12BjGVvOAgCq7LffPDKCW7zXI6wRc3dx0pklYWqZHXbNsMfx8xSN3lqJTYw6zLZGwt2MgcjajHa1AnMbTnZOjrq9WPZuFG0pyJj9ucKB0w/k4r123vOLzVI0pEISo3WTIDsfKMycIpGiNcDHdJIc2LQGG5Bum9TFJuUllpt5c5LQC9g1rKIS2nj55QCQ8a3EeeqDe3N85Sw6OT7k7oPkKVLPee5fAWfkQQqW1fmA7sGIWKDpVTi1Jq46I2MiJM+48m+rxOVEPXky3j8u8+lPWg6vOnKogoXTb52foAurmAA==" -X POST -d {\"version\":\"1.0\",\"session\":{\"new\":true,\"sessionId\":\"amzn1.echo-api.session.10759bc1-b5d1-4dbf-8aa0-006250acf94f\",\"application\":{\"applicationId\":\"amzn1.echo-sdk-ams.app.e78a3bfc-1d3a-41d4-be64-4a157cc27b85\"},\"user\":{\"userId\":\"amzn1.account.AFSNGQ7QZ4A5OBCCVVYGDXRCMSLQ\",\"accessToken\":\"token\"}},\"request\":{\"type\":\"LaunchRequest\",\"requestId\":\"amzn1.echo-api.request.bab8631b-7a08-4f62-a3d0-26e0de1495d3\",\"timestamp\":\"2015-10-07T16:48:23Z\"}} --verbose http://localhost:58080/alexa/sample-session
```

(note that when specifying a JSON payload to the cURL command line on Windows you have to escape the quotes, see http://stackoverflow.com/q/18314796/75426)

When this happens, AlexaSkillsKit.NET rejects the request (meaning it doesn't call your code) and returns HTTP status code 400 with a short description of the validation problem it detected. AlexaSkillsKit.NET also supports overriding the default request validation policy, see Advanced section in https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/blob/master/README.md

I just tested all the above using version 1.4.1 which the FreeBusy Scheduling Buddy skill is using in production so I have no idea why the cert team's test is failing and they are rejecting your skill. Can you ask them to tell you exactly what their test is checking for?

**Comment by brendan-murphy** [comment]
@rscott78 I realized that I am not using the Speechlet classes in my project because I have my own implementation of a similar class that I use so my issue might not be related. The Speechlet class verifies the date the same way that fixed my rejected submission by using the SpeechletRequestTimestampVerifier.VerifyRequestTimestamp function, so I am also unsure why your skill would be rejected.

**Comment by jimgardner99** [comment]
Looking at the Amazon documentation for verifying the certificate, it requires that the URL syntax be checked.  Could this be the issue since I don't see that the library checks for the following unless I'm just not finding it in the library:  

First, normalize the URL so that you can validate against a correctly formatted URL. For example, normalize

https://s3.amazonaws.com/echo.api/../echo.api/echo-api-cert.pem
to:
https://s3.amazonaws.com/echo.api/echo-api-cert.pem

Next, determine whether the URL meets each of the following criteria:
The protocol is equal to https (case insensitive).
The hostname is equal to s3.amazonaws.com (case insensitive).
The path starts with /echo.api/ (case sensitive).
If a port is defined in the URL, the port is equal to 443.

Examples of correctly formatted URLs:
https://s3.amazonaws.com/echo.api/echo-api-cert.pem
https://s3.amazonaws.com:443/echo.api/echo-api-cert.pem
https://s3.amazonaws.com/echo.api/../echo.api/echo-api-cert.pem

Examples of invalid URLs:
http://s3.amazonaws.com/echo.api/echo-api-cert.pem (invalid protocol)
https://notamazon.com/echo.api/echo-api-cert.pem (invalid hostname)
https://s3.amazonaws.com/EcHo.aPi/echo-api-cert.pem (invalid path)
https://s3.amazonaws.com/invalid.path/echo-api-cert.pem (invalid path)
https://s3.amazonaws.com:563/echo.api/echo-api-cert.pem (invalid port)

**Comment by jimgardner99** [comment]
This is the response I got back from Amazon:

Thanks for reaching out! As part of our certification process, we programmatically query your endpoint's certificates for validation. When doing so, we should not be receiving 'HttpHostConnectException: Connection to https://www.example.com:443 refused.' or similar exceptions. In addition, the skill should validate the signatures for incoming requests and should not accept requests with an invalid signature specified. For example, we expect to receive an HTTP code of ‘400’ for requests with an invalid signature, so your skill should not be responding with a ‘200’ code.

**Comment by stefann42** [comment]
@jimgardner99 Thanks for helping this investigation. With regards to your first message, the library does currently validate the certificate path, although not as comprehensively as the rules ask for. It uses regular expressions. The regex is defined at https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/blob/master/AlexaSkillsKit.Lib/Sdk.cs#L13 and used at https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/blob/master/AlexaSkillsKit.Lib/Authentication/SpeechletRequestSignatureVerifier.cs#L111 and it's meant to accept the most common formats of the certificate URL. As currently written it won't consider valid URLs those where the port is explicitly specified or those which are not nomalized. I haven't put in the time to support those because they are corner cases and the likelihood that Alexa service will ever use URLs formatted like that is very small. But it's straightforward to modify the regex to increase coverage of accepted formats if ever needed.

That being said, here's why this particular URL validation aspect isn't related to the cert rejection issue we're discussing here: the problem @rscott78 reported is about the library supposedly accepting a request with an invalid cert. The cases that the current regex doesn't cover are actually cases where a the library would reject a valid request. So, if anything, one can say the library is too strict not too lax.

Unfortunately the response from the cert team is too generic. Can you probe further on what _exactly_ the mean by "invalid signature" in 

> "we expect to receive an HTTP code of ‘400’ for requests with an invalid signature"

and what is the _exact_ test case that's failing? Ideally they would share with us the exact request they are sending so we can understand where it falls through the cracks, so-to-speak.

Thanks!

**Comment by jimgardner99** [comment]
@stefann42 Thanks for responding.  I believe the first issue with the SSL certificate has to do with our own SSL certificate.  They are trying to programmatically validate our SSL certificate at a URL such as https://www.example.com:443.  This would be a .NET WCF web application.  I'm guessing this may be a setting in IIS, but I can't seem to locate anything, and I don't have a lot of experience with certificates.  I know our certificate is valid.  Have you ever come across like this in the past?  Thanks.

**Comment by rscott78** [comment]
@stefann42 I talked to the Echo cert time (finally!) and they ran some tests and told me direction that my skill was failing because of what @jimgardner99 mentioned - specifically that my skill does not "Verify the Signature Certificate URL" correctly.

You can see the thread and their response here: https://forums.developer.amazon.com/forums/thread.jspa?forumID=93&threadID=11926

**Comment by jimgardner99** [comment]
@rscott78 @stefann42 I'm getting the same response:

Apologies for a long delay in replying back. The issue is question was because of the skill end-point was not validating the signatures for incoming requests and was accepting requests with an incorrect certificate URL. Please make sure that your signature validation is correct.

Before downloading the certificate from the URL specified in the SignatureCertChainUrl header, you should ensure that the URL represents a URL Amazon would use for the certificate. This protects against requests that attempt to make your web service download malicious files and similar attacks.

**Comment by rscott78** [comment]
@jimgardner99 Do you have a fix already in place for yours that you could share?

**Comment by jimgardner99** [comment]
@rscott78 I just resubmitted my app again with logging to see what is being sent for the Certificate URL.  I also changed the library to implement the Amazon checks including the port number.  It's a little confusing since the library as it existed should be even more restrictive.  But even if my code doesn't work, I will be able to see what is being sent for the certificate url.  I will let you know what happens.

**Comment by jimgardner99** [comment]
My app finally got approved today.  I added code to VerifyRequestSignature.  It's not the most elegant, but it implements the checks Amazon is asking for.  You can take out the Log references if needed.

            // https://s3.amazonaws.com/echo.api/echo-api-cert-3.pem
            Log.Info("Cert URL: " + certChainUrl);
            Log.Info("Signature: " + expectedSignature);

            if (!String.IsNullOrEmpty(certChainUrl))
            {
                if ((certChainUrl.Length >= 8) && (certChainUrl.Substring(0, 8).ToLower() != "https://"))
                {
                    Log.Info("Cert URL doesn't start with https://");
                    return false;
                }
                if ((certChainUrl.Length >= 24) && (certChainUrl.Substring(0, 24).ToLower() != "https://s3.amazonaws.com"))
                {
                    Log.Info("Cert URL hostname is not s3.amazonaws.com");
                    return false;
                }
                if (!certChainUrl.Contains("/echo.api/echo-api-cert"))
                {
                    //Log.Info(certChainUrl.Substring(certChainUrl.Length - 27));
                    Log.Info("Cert URL path is not /echo.api");
                    return false;
                }

                string portTest = certChainUrl.ToLower().Split(':', '/')[1];
                if (!String.IsNullOrEmpty(portTest))
                {
                    if (portTest != "443")
                    {
                        Log.Info("Cert URL port is not 443");
                        return false;
                    }
                }
            }

In RetrieveAndVerifyCertificate, I commented out:

// if (!Regex.IsMatch(certChainUrl, Sdk.SIGNATURE_CERT_URL_MASK_REGEX)) return null;

**Comment by unaware1224** [comment]
I am not sure how you got your skill approved ... I had to change the cache key for the certs before mine got approved, see pull #9

**Comment by jimgardner99** [comment]
Thanks @unaware1224.  I just upgraded to your latest pull #9.  I will be sending a new version to Amazon for certification this week so I will let you know how it goes.

**Comment by smussani** [comment]
Hi Guys,
Our skill got rejected due to the same issue.  I have implemented the changes mentioned in pull #9. I was hoping to test it using Fiddler.  Can someone help with steps on how to test it before I submit to Amazon?
Thanks

**Comment by smussani** [comment]
After applying changes from pull #9, our skill was approved by Amazon cert team.  thanks for posting it

**Comment by stefann42** [comment]
Hi everyone, thanks for your effort to figure out this particular issue and sorry for the delayed response. Release 1.5.0 now has certificate URL verification logic as in PR https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/pull/9. My comment to the PR explains why I reimplemented rather than accept the PR. The examples given by Amazon in the docs and pasted above are now in a [unit test](https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/blob/master/AlexaSkillsKit.Tests/Authentication/SignatureVerifierTests.cs) and the implementation is also consistent with Amazon's own [getAndVerifySigningCertificateChainUrl](https://github.com/amzn/alexa-skills-kit-java/blob/master/src/com/amazon/speech/speechlet/authentication/SpeechletRequestSignatureVerifier.java#L197) in the official Java version of SDK.

Per @unaware1224 it seems that for his skill he also needed a change to the way certificate caching works to pass certification, but that's not confirmed by others and I don't believe it's needed (or better said, I would like to understand _why_ it's needed because I can't find substanting docs).

I'll leave this issue open until someone confirms that they passed certification with v1.5.0. Thanks all!

**Comment by olipachi** [comment]
So I've tried to pass certification from Amazon, and got the same feedback @jimgardner99  did. They're exact feedback was:

"The skill end-point is not validating the signatures for incoming requests and is accepting requests with an incorrect certificate URL. Please make sure that your signature validation is correct.
Please refer to the following documentation on how to build your Alexa Skill as a web service and validate requests and signatures.  
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/developing-an-alexa-skill-as-a-web-service#verifying-the-signature-certificate-url"

I'm running v 1.5.0, and since it has failed, I wanted to try the changes mention in PR #9, but am having issues doing that.  Can anyone help me out here? Greatly appreciated :)

**Comment by stefann42** [comment]
Hi @olipachi, I reached out to the Alexa SDK team to request more information about the certification test suite that's reporting this failure. Will update the thread as soon as a I hear back with details.

**Comment by olipachi** [comment]
@stefann42 Great, thanks! I've also got some correspondence with the people at Alexa SDK, so let me know if there's anything I may be able to assist with in expediting the process. I really don't wanna rewrite this whole skill in Java just to satisfy validation. :)

**Comment by stefann42** [comment]
@olipachi I received this initial response, still waiting to hear why your skill was rejected still
> Based on the discussion in https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/issues/5 (started in March), the latest fix implemented by @stefann42  in https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/commit/09655a20de58c10 (from May) is compatible with our internal checks and takes care of the scenario when we give feedback "The skill end-point is not validating the signatures for incoming requests and is accepting requests with an incorrect certificate URL... ". We check for invalid URLs nothing above and beyond what’s in the docs.

**Comment by olipachi** [comment]
Thanks @stefann42, I will check again with them and see what's up. Thanks a lot for the quick support for this.

**Comment by jimgardner99** [comment]
Hi @olipachi.  I've gotten two versions passed with no issues using pull #9.

**Comment by stefann42** [comment]
@olipachi Please email me the Skill ID for your skill that got rejected so I can be more specific in the conversation with the certification team. My email is stefan@freebusy.io.

**Comment by rosariomartone** [comment]
Hi,
thank to all of you for your posts.
I have an issue regarding how passing the url to validate:

        [HttpPost, Route("api/alexa/tombolina")]
        public dynamic Tombolina(AlexaRequest alexaRequest)
        {
            AlexaResponse response = null;

            if(SpeechletRequestSignatureVerifier.VerifyCertificateUrl(<URL TO VALIDATE>))
            {
                Request request = new Data.Request();
                request.MemberId = (alexaRequest.Session.Attributes == null) ? 0 : alexaRequest.Session.Attributes.MemberId;
                request.Timestamp = alexaRequest.Request.Timestamp;
                request.Intent = (alexaRequest.Request.Intent == null) ? "" : alexaRequest.Request.Intent.Name;
                request.AppId = alexaRequest.Session.Application.ApplicationId;
                request.RequestId = alexaRequest.Request.RequestId;
                request.SessionId = alexaRequest.Session.SessionId;
 ...

I have tried using this.Request.RequestUri.AbsoluteUri but I receive the path where the my controller is (https://www.rosariomartone.co.uk/api/alexa/tombolina. Should I receive the URL of the real calling url? In case of Alexa something like https://s3.amazonaws.com/echo.api/echo-api-cert.pem?

Thanks!
Ros.

**Comment by stefann42** [comment]
@rosariomartone please open a new issue since what you are asking is unrelated to this particular issue. In short, you are using the library incorrectly. `VerifyCertificateUrl` is an internal function not meant to be called by you (should have probably been marked `private`). There is no need to you to perform certificate validation explicitly. It's something the library does implicitly.

**Comment by rosariomartone** [comment]
Hi @stefann42 , thanks for your tip.
What I am trying to do actually is using your API with the following method:

[HttpPost, Route("api/alexa/tombolina")]
        public dynamic Tombolina(AlexaRequest alexaRequest)
        {
            AlexaResponse response = null;

            var speechlet = new SessionSpeechLet();
            HttpResponseMessage check = null;

            try
            {
                check = speechlet.GetResponse(Request);
            }
            catch(Exception ex)
            {
                check = new HttpResponseMessage(HttpStatusCode.Conflict);
            }

            if (check.StatusCode.Equals(HttpStatusCode.OK))
            {
                Request request = new Data.Request();
                request.MemberId = (alexaRequest.Session.Attributes == null) ? 0 : alexaRequest.Session.Attributes.MemberId;
                request.Timestamp = alexaRequest.Request.Timestamp;
                request.Intent = (alexaRequest.Request.Intent == null) ? "" : alexaRequest.Request.Intent.Name;
                request.AppId = alexaRequest.Session.Application.ApplicationId;
                request.RequestId = alexaRequest.Request.RequestId;
                request.SessionId = alexaRequest.Session.SessionId;
                request.UserId = alexaRequest.Session.User.UserId;
                request.IsNew = alexaRequest.Session.New;
                request.Version = alexaRequest.Version;
                request.Type = alexaRequest.Request.Type;
                request.Reason = alexaRequest.Request.Reason;
                request.SlotsList = alexaRequest.Request.Intent.GetSlots();
                request.DateCreated = DateTime.UtcNow;

                switch (request.Type)
                {
                    case "LaunchRequest":
                        response = LaunchRequestHandler(request);

                        break;
                    case "IntentRequest":
                        response = IntentRequestHandler(request);

                        break;
                    case "SessionEndedRequest":
                        response = SessionEndedRequestHandler(request);

                        break;
                }

                return response;
            }
            else
                return new HttpResponseMessage(HttpStatusCode.BadRequest);
        }

Thing is the following line is failing:

 check = speechlet.GetResponse(Request);

Because the Request object is NULL, could you please help me to understand why?

**Comment by smoore4moma** [comment]
One thing to watch out for is web.config.  Most of us were taught to hide errors from users, so it is common to redirect ANY error to an error page, like this:

`<customErrors mode="On" defaultRedirect="~/Home/Error" /> `

I changed this to `<customErrors mode="Off" />` and that worked.  Not a AreYouFreeBusy app but might be relevant anyway.
