### ISSUE TITLE
Alexla custom skill-There was an error calling the remote endpoint, which returned HTTP 500 : Internal Server Error

### ISSUE THREAD

**Issue by koushikmondal2** [AreYouFreeBusy/AlexaSkillsKit.NET#60]
I have created a custom skill set and have hosted it on Azure cloud. When I try to test my service request using developer portal, I get the following error, "There was an error calling the remote endpoint, which returned HTTP 500 : Internal Server Error"

I have Hosted my Alexa skill set endpoint in the sub-domain of azure. e.g. https://alexaforg3ms.azurewebsites.net/api/alexa/demo

For testing purposes when I try to send a request to the Alexa skill set end point through Fiddler, it gives me a status called - 415 {"Message":"The request contains an entity body but no Content-Type header. The inferred media type 'application/octet-stream' is not supported for this resource."}

Should I be using Lambda ?

Any help in this area would be appreciated.

**Comment by cschwendtner** [comment]
@koushikmondal2 Hosting your skill on Azure should work (my skill is hosted on Azure too and it works smoothly).

When you test your skill (with a tool) you have to set the Content-Type header to application/json. 
I have built a sample request for your service (see https://client.restlet.com/#share=https://client.restlet.com/api/share/5a4e0756a0b6db0ad3b678d9) - I get Bad Request.

I would test my skills locally. You can do this by using tools like [ngrok](https://ngrok.com/) or [localtunnel](https://github.com/localtunnel/localtunnel). With those tools, requests to a public https URL are tunneled to localhost. So you can invoke your skill through the developer portal (or your Alexa device - e.g. an Echo) and test / debug locally.

I currently use localtunnel. Sample usage:
lt --port 9000 --subdomain myfancysubdomain --local-host localhost

That gives you 
https://myfancysubdomain.localtunnel.me which tunnels requests to http://localhost:9000

So a request to https://myfancydomain.localtunnel.me/api/alexa/demo is tunneled to http://localhost:9000/api/alexa/demo

--port: The local port on which your application listens
--subdomain: I use a GUID for that (to avoid conflicts), so that I can use the same subdomain again and again and do not have to change the endpoint in the Amazon developer portal every time I start localtunnel (if you don't use --subdomain you get a random URL).
--local-host: Rewrites the Host header of the request to (in this example) localhost. Needed if you are using for example IISExpress on localhost so that the request is accepted.

The tool localtunnel crashes some times (at least on my machine) ... so I use a script that starts localtunnel again when it crashed.

**Comment by koushikmondal2** [comment]
@cschwendtner Thanks for helping. Issue is fixed now.
