### ISSUE TITLE
Alexa live skill stoped working suddenly

### ISSUE THREAD

**Issue by gauravbhavsar** [AreYouFreeBusy/AlexaSkillsKit.NET#83]
Suddenly Alexa stop working and responded as

>Sorry, I'm having trouble accessing your Polymer Update Skill right now

I have debug the dev skill and it is responded as

> The skill responded with 400 HTTP status code

Do I need to change the format of response ? Now I am using `public HttpResponseMessage GetResponse(HttpRequestMessage httpRequest)` method of `AlexaSkillKit version 1.6.0.0` and returning `SpeechletResponse` as response

**Comment by gauravbhavsar** [comment]
I have got the response from Alexa team as
>You're using your own server to host the back-end of this Alexa skill here [httpPath]. (As we are using our own server to hosted the API).

>When we send this back-end requests though, it's responding with Error Code 400 Bad Request with a reason of "InvalidTimestamp". Given that, it looks like the issue is being caused by this self-hosted back-end not properly validating the the timestamps of requests. 

Now how do I validate the TimeStamp ? I read the documentation and SDK already having constant property as `public const int TIMESTAMP_TOLERANCE_SEC = 150;`

Please help me to crack this situation.

**Comment by stefann42** [comment]
Hi @gauravbhavsar, timestamp validation works by comparing the difference between the timestamp received from the Alexa service and the current time on your server as you can see at
https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/blob/master/AlexaSkillsKit.Lib/Authentication/SpeechletRequestTimestampVerifier.cs
and
https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/blob/60179d0a581d2dd1286d7b3806fa93663a9c7d61/AlexaSkillsKit.Lib/Speechlet/SpeechletService.cs#L136

So, one reason timestamp validation could be failing is because the time on your server is not synchronized. Make sure your server synchronizes its clock to a well known NTP service. 

If you don't have control over the server to ensure the clock is correctly set, turn off timestamp validation in your skill by overridding the request validation policy as described at https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET#override-request-validation-policy

**Comment by gauravbhavsar** [comment]
didn't notice server time is behind the current time by 7 minutes, Thanks @stefann42 to point out the server time.
